include ../Makefile.conf

PROGRAMS=get_min_max_sum \
         contains \
         sort1 \
         sort2 \
         point2d \
         pair \
         simple_vector_template \

all: $(PROGRAMS)

clean: 
	rm -f $(PROGRAMS)

