include ../Makefile.conf

PROGRAMS= point2d interval struct_alignment reverse \
          cstring_functions structs_and_arrays range_based_for_loops \
	  buffer_overflow_1 buffer_overflow_2

all: $(PROGRAMS)

clean: 
	rm -f $(PROGRAMS)

