include ../Makefile.conf

PROGRAMS= pointer_basics \
	  pointers_and_arrays \
          pointer_buffer_overflow \
 	  arrays_of_pointers \
 	  main_with_args \
	  pointers_and_structs \
	  null_pointer \
	  main_with_env_args \
	  pointer_arithmetic \
          cstring_functions \
          reverse \

all: $(PROGRAMS)

clean: 
	rm -f $(PROGRAMS)

