include ../Makefile.conf

PROGRAMS=string_examples \
         string_range_based_for_loops \
         heterogram \
         read_and_sort_values \
	 ifstream_sum \
	 error_recovery


all: $(PROGRAMS)

clean: 
	rm -f $(PROGRAMS)

