include ../Makefile.conf

PROGRAMS = \
deque_example \
erase_example \
map_example \
multimap_example \
multiset_example \
reverse_iterator_example \
set_example \
sorting_examples \
sorting_examples2 \
vector_iterators

all: $(PROGRAMS)

clean: 
	rm -fr $(PROGRAMS) *dSYM

