include ../Makefile.conf

PROGRAMS = \
deque_example \
emplace_example \
iterator_example \
iterator_example2 \
map_example \
map_example2 \
multimap_example \
multiset_example \
set_example \
set_example2 \
sorting_examples \
sorting_examples2 

all: $(PROGRAMS)

clean: 
	rm -fr $(PROGRAMS) *dSYM

