name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout from Git'
        uses: actions/checkout@v2
      - name: 'Display GCC version'
        run: g++ --version
      - name: 'Compile'
        run: make
